--------------------------------------------------------
-- Archivo creado  - sábado-febrero-20-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COSTO
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."COSTO" 
   (	"IDCOSTO" NUMBER(*,0), 
	"COSTOADICIONAL" VARCHAR2(20 BYTE), 
	"ENVIO" NUMBER(*,0), 
	"IDPRODUCTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."USUARIO" 
   (	"IDUSUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"NICK" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"IDROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."PRODUCTO" 
   (	"IDPRODUCTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"MARCA" VARCHAR2(20 BYTE), 
	"TIPO" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RUTA
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."RUTA" 
   (	"IDRUTA" NUMBER(*,0), 
	"RUTA1" VARCHAR2(20 BYTE), 
	"RUTA2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."ROL" 
   (	"IDROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(128 BYTE), 
	"DESCRIPCION" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAQUETE
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."PAQUETE" 
   (	"IDPAQUETE" NUMBER(*,0), 
	"RECEPTOR" VARCHAR2(20 BYTE), 
	"EMISOR" VARCHAR2(20 BYTE), 
	"FECHAENTREGA" VARCHAR2(20 BYTE), 
	"FECHAEMISION" VARCHAR2(20 BYTE), 
	"IDPRODUCTO" NUMBER(*,0), 
	"IDRUTA" NUMBER(*,0), 
	"IDCOSTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICACION
--------------------------------------------------------

  CREATE TABLE "SISTEMAPAQUETES"."NOTIFICACION" 
   (	"IDNOTIFICACION" NUMBER(*,0), 
	"MENSAJE" VARCHAR2(20 BYTE), 
	"FECHA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COSTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."COSTO_PK" ON "SISTEMAPAQUETES"."COSTO" ("IDCOSTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."TABLE1_PK" ON "SISTEMAPAQUETES"."USUARIO" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."PRODUCTO_PK" ON "SISTEMAPAQUETES"."PRODUCTO" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RUTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."RUTA_PK" ON "SISTEMAPAQUETES"."RUTA" ("IDRUTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."ROL_PK" ON "SISTEMAPAQUETES"."ROL" ("IDROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PAQUETE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."PAQUETE_PK" ON "SISTEMAPAQUETES"."PAQUETE" ("IDPAQUETE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOTIFICACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SISTEMAPAQUETES"."NOTIFICACION_PK" ON "SISTEMAPAQUETES"."NOTIFICACION" ("IDNOTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COSTO
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."COSTO" ADD CONSTRAINT "COSTO_PK" PRIMARY KEY ("IDCOSTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."COSTO" MODIFY ("IDCOSTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."USUARIO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."USUARIO" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."PRODUCTO" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUTA
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."RUTA" ADD CONSTRAINT "RUTA_PK" PRIMARY KEY ("IDRUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."RUTA" MODIFY ("IDRUTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."ROL" ADD CONSTRAINT "ROL_PK" PRIMARY KEY ("IDROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."ROL" MODIFY ("IDROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PAQUETE
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."PAQUETE" ADD CONSTRAINT "PAQUETE_PK" PRIMARY KEY ("IDPAQUETE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."PAQUETE" MODIFY ("IDPAQUETE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTIFICACION
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."NOTIFICACION" ADD CONSTRAINT "NOTIFICACION_PK" PRIMARY KEY ("IDNOTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."NOTIFICACION" MODIFY ("IDNOTIFICACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COSTO
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."COSTO" ADD CONSTRAINT "COSTO_FK1" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "SISTEMAPAQUETES"."PRODUCTO" ("IDPRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."USUARIO" ADD CONSTRAINT "USUARIO_FK1" FOREIGN KEY ("IDROL")
	  REFERENCES "SISTEMAPAQUETES"."ROL" ("IDROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAQUETE
--------------------------------------------------------

  ALTER TABLE "SISTEMAPAQUETES"."PAQUETE" ADD CONSTRAINT "PAQUETE_FK1" FOREIGN KEY ("IDPRODUCTO")
	  REFERENCES "SISTEMAPAQUETES"."PRODUCTO" ("IDPRODUCTO") ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."PAQUETE" ADD CONSTRAINT "PAQUETE_FK2" FOREIGN KEY ("IDRUTA")
	  REFERENCES "SISTEMAPAQUETES"."RUTA" ("IDRUTA") ENABLE;
  ALTER TABLE "SISTEMAPAQUETES"."PAQUETE" ADD CONSTRAINT "PAQUETE_FK3" FOREIGN KEY ("IDCOSTO")
	  REFERENCES "SISTEMAPAQUETES"."COSTO" ("IDCOSTO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger COSTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."COSTO_TRG" 
BEFORE INSERT ON COSTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCOSTO IS NULL THEN
      SELECT COSTO_SEQ.NEXTVAL INTO :NEW.IDCOSTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."COSTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TABLE1_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."TABLE1_TRG" 
BEFORE INSERT ON USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDUSUARIO IS NULL THEN
      SELECT ROL_SEQ.NEXTVAL INTO :NEW.IDUSUARIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."TABLE1_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."PRODUCTO_TRG" 
BEFORE INSERT ON PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDPRODUCTO IS NULL THEN
      SELECT PRODUCTO_SEQ.NEXTVAL INTO :NEW.IDPRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."PRODUCTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RUTA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."RUTA_TRG" 
BEFORE INSERT ON RUTA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDRUTA IS NULL THEN
      SELECT RUTA_SEQ.NEXTVAL INTO :NEW.IDRUTA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."RUTA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ROL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."ROL_TRG" 
BEFORE INSERT ON ROL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NOMBRE IS NULL THEN
      SELECT ROL_SEQ.NEXTVAL INTO :NEW.NOMBRE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."ROL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PAQUETE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."PAQUETE_TRG" 
BEFORE INSERT ON PAQUETE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."PAQUETE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICACION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SISTEMAPAQUETES"."NOTIFICACION_TRG" 
BEFORE INSERT ON NOTIFICACION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDNOTIFICACION IS NULL THEN
      SELECT NOTIFICACION_SEQ.NEXTVAL INTO :NEW.IDNOTIFICACION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SISTEMAPAQUETES"."NOTIFICACION_TRG" ENABLE;
